name: leetcode
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dotenv: ^4.2.0
  mongo_dart: ^0.10.1

dev_dependencies:
  leetcode_api_dart: ^0.0.1
  lints: ^3.0.0
  test: ^1.24.0
